/**
 * Authentication routes — powered by better-auth.
 *
 * All /api/auth/* paths are delegated to the better-auth handler which
 * manages email/password sign-up, sign-in, session management, phone OTP,
 * and Expo session tokens.
 *
 * The handler accepts any method (GET, POST, PUT, DELETE) so we register a
 * wildcard route and forward the raw Request to auth.handler().
 *
 * Endpoints (auto-generated by better-auth):
 *   POST /api/auth/sign-up/email
 *   POST /api/auth/sign-in/email
 *   POST /api/auth/sign-out
 *   GET  /api/auth/session
 *   POST /api/auth/phone-number/send-otp
 *   POST /api/auth/phone-number/verify-otp
 *   GET  /api/auth/callback/:provider   (OAuth providers)
 *   GET  /api/auth/error
 */

import { Elysia } from "elysia";
import { auth } from "../lib/auth";
import { authRateLimiter } from "../lib/rateLimiter";

export const authRoutes = new Elysia({ prefix: "/api/auth" })
  // Rate-limit all auth endpoints by IP address.
  // Auth requests are pre-authentication (no userId available), so we key by IP.
  // Limit: 10 requests / IP / minute — prevents brute-force, credential stuffing, OTP enumeration.
  .onBeforeHandle(async ({ request, set }) => {
    const ip =
      request.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ??
      request.headers.get("x-real-ip") ??
      "unknown";
    const rl = await authRateLimiter.check(ip);
    if (!rl.allowed) {
      set.status = 429;
      const retryAfterSecs = Math.ceil(rl.resetIn / 1000);
      set.headers = { "Retry-After": String(retryAfterSecs) };
      return { error: "Too many requests. Please try again later." };
    }
  })
  // Wildcard GET — handles session check, OAuth callbacks, and error pages
  .get("/*", async ({ request }) => {
    return auth.handler(request);
  })
  // Wildcard POST/PUT/DELETE — handles sign-up, sign-in, sign-out, OTP verify, etc.
  .post("/*", async ({ request }) => {
    return auth.handler(request);
  })
  .put("/*", async ({ request }) => {
    return auth.handler(request);
  })
  .delete("/*", async ({ request }) => {
    return auth.handler(request);
  });
