/**
 * ProactiveHealthSuggestions
 *
 * Renders personalised health recommendations generated by
 * `proactiveHealthSuggestionsService`, and optionally the top health discovery
 * from `discoveryService` when `showDiscoveries` is true.
 *
 * The component is intentionally lightweight: it shows at most 3 suggestions
 * and 1 discovery to keep the home-screen card compact.
 */

import React, { useEffect, useState, useCallback } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
} from 'react-native';
import { router } from 'expo-router';
import { Lightbulb, ChevronRight, Dna } from 'lucide-react-native';
import { useTranslation } from 'react-i18next';
import { useAuth } from '@/contexts/AuthContext';
import { proactiveHealthSuggestionsService, type HealthSuggestion } from '@/lib/services/proactiveHealthSuggestionsService';
import { discoveryService, type EnrichedDiscovery } from '@/lib/services/discoveryService';

interface ProactiveHealthSuggestionsProps {
  showDiscoveries?: boolean;
}

const PRIORITY_COLOR: Record<string, string> = {
  high:   '#DC2626',
  medium: '#D97706',
  low:    '#2563EB',
};

export default function ProactiveHealthSuggestions({ showDiscoveries = false }: ProactiveHealthSuggestionsProps) {
  const { t, i18n } = useTranslation();
  const { user } = useAuth();
  const isRTL = i18n.language === 'ar';

  const [suggestions, setSuggestions] = useState<HealthSuggestion[]>([]);
  const [topDiscovery, setTopDiscovery] = useState<EnrichedDiscovery | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(async () => {
    if (!user?.id) { setLoading(false); return; }
    try {
      const [sugs, discoveries] = await Promise.allSettled([
        proactiveHealthSuggestionsService.generateSuggestions(user.id, isRTL),
        showDiscoveries
          ? discoveryService.getTopDiscoveries(user.id, 1, isRTL)
          : Promise.resolve([]),
      ]);

      if (sugs.status === 'fulfilled') {
        setSuggestions(sugs.value.filter((s) => !s.dismissed).slice(0, 3));
      }
      if (discoveries.status === 'fulfilled' && discoveries.value.length > 0) {
        setTopDiscovery(discoveries.value[0]);
      }
    } catch (err) {
      console.warn('[ProactiveHealthSuggestions] Failed to load suggestions:', err);
    } finally {
      setLoading(false);
    }
  }, [user?.id, isRTL, showDiscoveries]);

  useEffect(() => { load(); }, [load]);

  if (loading) {
    return (
      <View style={styles.loadingRow}>
        <ActivityIndicator size="small" color="#2563EB" />
      </View>
    );
  }

  const hasContent = suggestions.length > 0 || topDiscovery != null;
  if (!hasContent) return null;

  return (
    <View style={styles.container}>
      {/* ── Health Suggestions ───────────────────────────────────────── */}
      {suggestions.length > 0 && (
        <>
          <Text style={[styles.sectionTitle, isRTL && styles.rtl]}>
            {isRTL ? 'توصيات صحية' : 'Health Recommendations'}
          </Text>
          {suggestions.map((sug) => {
            const accent = PRIORITY_COLOR[sug.priority] ?? PRIORITY_COLOR.medium;
            return (
              <TouchableOpacity
                key={sug.id}
                style={[styles.card, { borderLeftColor: accent }]}
                activeOpacity={sug.action?.route ? 0.7 : 1}
                onPress={() => sug.action?.route && router.push(sug.action.route as never)}
              >
                <Lightbulb size={15} color={accent} style={styles.icon} />
                <View style={styles.cardBody}>
                  <Text style={[styles.cardTitle, isRTL && styles.rtl]}>{sug.title}</Text>
                  <Text style={[styles.cardDesc, isRTL && styles.rtl]}>{sug.description}</Text>
                  {sug.action?.label && (
                    <Text style={[styles.actionLabel, { color: accent }, isRTL && styles.rtl]}>
                      {sug.action.label}
                    </Text>
                  )}
                </View>
                {sug.action?.route && (
                  <ChevronRight size={14} color="#9CA3AF" style={isRTL ? styles.chevronRTL : undefined} />
                )}
              </TouchableOpacity>
            );
          })}
        </>
      )}

      {/* ── Top Discovery ─────────────────────────────────────────────── */}
      {showDiscoveries && topDiscovery && (
        <>
          <Text style={[styles.sectionTitle, { marginTop: suggestions.length > 0 ? 12 : 0 }, isRTL && styles.rtl]}>
            {isRTL ? 'اكتشاف صحي' : 'Health Discovery'}
          </Text>
          <TouchableOpacity
            style={[styles.card, styles.discoveryCard]}
            activeOpacity={0.7}
            onPress={() => router.push('/(tabs)/track' as never)}
          >
            <Dna size={15} color="#7C3AED" style={styles.icon} />
            <View style={styles.cardBody}>
              <Text style={[styles.cardTitle, isRTL && styles.rtl]}>
                {isRTL ? (topDiscovery.titleAr ?? topDiscovery.title) : topDiscovery.title}
              </Text>
              {topDiscovery.description != null && (
                <Text style={[styles.cardDesc, isRTL && styles.rtl]}>
                  {isRTL
                    ? (topDiscovery.descriptionAr ?? topDiscovery.description)
                    : topDiscovery.description}
                </Text>
              )}
            </View>
            <ChevronRight size={14} color="#9CA3AF" style={isRTL ? styles.chevronRTL : undefined} />
          </TouchableOpacity>
        </>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { marginBottom: 4 },
  loadingRow: { alignItems: 'center', paddingVertical: 8 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#2563EB',
    padding: 10,
    marginBottom: 6,
  },
  discoveryCard: {
    borderLeftColor: '#7C3AED',
    backgroundColor: '#FAF5FF',
  },
  icon: { marginTop: 1, marginRight: 8 },
  cardBody: { flex: 1 },
  cardTitle: { fontSize: 13, fontWeight: '600', color: '#111827', marginBottom: 2 },
  cardDesc: { fontSize: 12, color: '#4B5563', lineHeight: 17 },
  actionLabel: { fontSize: 11, fontWeight: '600', marginTop: 4 },
  rtl: { textAlign: 'right' },
  chevronRTL: { transform: [{ scaleX: -1 }] },
});
