/**
 * useDailyBriefing hook
 * Reads today's AI-generated daily briefing from Firestore.
 */

import { useEffect, useRef, useState } from "react";
import { api } from "@/lib/apiClient";

export type DailyBriefing = {
  summary: string;
  summaryAr?: string; // Arabic translation — generated by Cloud Function
  score?: number;
  highlights: string[];
  highlightsAr?: string[];
  generatedAt: Date;
};

type UseDailyBriefingReturn = {
  briefing: DailyBriefing | null;
  loading: boolean;
  hasBriefing: boolean;
  isToday: boolean;
};

function getTodayKey(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

export function useDailyBriefing(
  userId: string | undefined
): UseDailyBriefingReturn {
  const [briefing, setBriefing] = useState<DailyBriefing | null>(null);
  const [loading, setLoading] = useState(false);
  const fetchedRef = useRef(false);

  useEffect(() => {
    if (!userId || fetchedRef.current) return;
    fetchedRef.current = true;

    setLoading(true);

    const todayKey = getTodayKey();

    api.get<Record<string, unknown> | null>(
      `/api/health/briefings/${todayKey}`
    )
      .catch(() => null)
      .then((raw) => {
        if (raw) {
          const data = raw;
          setBriefing({
            summary: data.summary as string,
            summaryAr: data.summaryAr as string | undefined,
            score: data.score as number | undefined,
            highlights: (data.highlights as string[]) ?? [],
            highlightsAr: (data.highlightsAr as string[]) ?? [],
            generatedAt: data.generatedAt
              ? new Date(data.generatedAt as string)
              : new Date(),
          });
        }
      })
      .catch(() => {
        // Silently fail — briefing is a nice-to-have enhancement
      })
      .finally(() => setLoading(false));
  }, [userId]);

  const isToday =
    briefing !== null &&
    briefing.generatedAt.toDateString() === new Date().toDateString();

  return {
    briefing,
    loading,
    hasBriefing: briefing !== null,
    isToday,
  };
}
